<?php

/**
 * @file
 * Install, update and uninstall functions for GPT.
 */

/**
 * TODO: Need hook_update_N to migrate from src/prep storage to new.
 */

/**
 * Implements hook_uninstall().
 */
function gpt_uninstall() {
  // Remove module variables
  $result = db_query('SELECT name FROM {variable} WHERE name LIKE :name', array(
    ':name' => 'gpt__%',
  ));
  foreach ($result as $record) {
    variable_del($record->name);
  }
}
