<?php

/**
 * @file
 * Install, update and uninstall functions for GPT Entity Targeting.
 */

/**
 * Implements hook_schema().
 */
function gpt_entity_schema() {
  $schema = array();

  $schema['gpt_entity'] = array(
    'fields' => array(
      'entity_type' => array(
        'type' => 'varchar',
        'length' => 32,
        'not null' => TRUE,
        'default' => '',
        'description' => 'The entity type this data is attached to',
      ),
      'entity_id' => array(
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
        'description' => 'The entity id this data is attached to',
      ),
      'data' => array(
        'type' => 'blob',
        'size' => 'big',
        'not null' => TRUE,
        'serialize' => TRUE,
      ),
    ),
    'primary key' => array('entity_type', 'entity_id'),
  );

  return $schema;
}

/**
 * TODO: Need hook_update_N to migrate from src/prep storage to new.
 */

/**
 * Implements hook_uninstall().
 */
function gpt_entity_uninstall() {
  // Remove module variables
  $result = db_query('SELECT name FROM {variable} WHERE name LIKE :name', array(
    ':name' => 'gpt_entity__%',
  ));
  foreach ($result as $record) {
    variable_del($record->name);
  }
}